version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: app
    tty: true
    volumes:
      - .:/app
      - ${HOME}/.cache/composer:/home/application/.composer/cache
    environment:
      - APP_ENV=local
    ports:
      - 8080:80
    networks:
      - network_app

networks:
  network_app:
    driver: "bridge"
