version: '3.1'
services:

  server:
      image: nginx:alpine
      restart: unless-stopped
      working_dir: /application
      volumes:
        - ../:/application
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        #- /etc/letsencrypt/archive/{dominio}:/etc/nginx/certs/
      expose:
        - 80
      ports:
        - ${APP_PORT}:80
      depends_on:
        - mysql
        - redis
      logging:
            driver: "json-file"
            options:
              max-size: "200k"
              max-file: "10"

  php-fpm:
      build:
        context: ./php
        dockerfile: Dockerfile
      restart: unless-stopped
      working_dir: /application
      volumes:
        - ../:/application
        - ./php/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
        - ${HOME}/.cache/composer:/home/user/.composer/cache

  mysql:
        image: 'mysql:5.7'
        restart: unless-stopped
        container_name: ${DB_HOST}
        volumes:
          - ${DB_VOLUMEN}:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
          - MYSQL_DATABASE=${DB_DATABASE}
          - MYSQL_USER=${DB_USERNAME}
          - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
          - ${DB_PORT}:3306
        logging:
              driver: "json-file"
              options:
                max-size: "200k"
                max-file: "10"
  redis:
      image: redis
      restart: unless-stopped
      working_dir: /application
      ports:
          - ${REDIS_PORT}:6379
      logging:
            driver: "json-file"
            options:
              max-size: "200k"
              max-file: "10"
